[package]
name = "loveletter"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "ğŸŸ â† ğŸ’Œ â† ğŸ“¬ â† ğŸ’Œ â† ğŸ¦¢"
homepage = "https://github.com/SilverRainZ/loveletter"
repository = "https://github.com/SilverRainZ/loveletter"
readme = "README.md"
categories = ["command-line-utilities", "email"]
keywords = ["email", "loveletter"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.34", features = ["derive"] }
email_address = "0.2.9"
imap = { version = "3.0.0-alpha.15", features = ["native-tls"] }
log = "0.4.27"
mail-parser = "0.10.2"
serde = "1.0.219"
serde_derive = "1.0.219"
signal-hook = "0.3.17"
simplelog = "0.12.2"
toml = "0.8.20"
unicode-width = "0.2.0"
xshell = "0.2.7"

[dev-dependencies]
ctor = "0.4.1"
tempfile = "3.19.1"
